# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c19b3c5031da365103bfdbe39b670ebe6a7612bca67366d7ae25a30952e57a97ae923e7e13e85a5898cee8314cd33971f56141537e10bc3da6dec8337328a7b

test:
  secret_key_base: 7a1986be55b085e183dc027bac44f737a676e54aff9e56616b257934cfd2463024385694ccdbce90d4e6a06e5fc9ad80170f846bceee17bc9054f2cec065bca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
